apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bfstats-ui
  namespace: bfstats-ui
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`1942.home.net`)
    kind: Rule
    services:
    - name: bfstats-ui-service
      port: 80
